### ISSUE TITLE
Vote pages behaviour

### ISSUE THREAD

**Issue by benparsons** [emojirank/web#12]
1. user hits / they are redirected to a random emoji specific page
2. user hits /emoji/<unicode_character> they get that emoji to vote on
3. user presses the next button (at any time) and they are taken to a new page with a new url, i.e. they go to step 2.

@pixlwave can you confirm this, will take a little work to make it behave this way compared to what it does now.

**Comment by pixlwave** [comment]
Yes, that sounds correct!
