### ISSUE TITLE
Results per-emoji should appear after all voting is done

### ISSUE THREAD

**Issue by benparsons** [emojirank/web#2]
What data should be shown? Most liked, most hated?

**Comment by pixlwave** [comment]
Initially just most liked & most hated will be fine. Once there is a bigger data set we could investigate other interesting results too.

**Comment by pixlwave** [comment]
Oh, also, vendor needs to be revealed with the results.

**Comment by benparsons** [comment]
This is all done, just needs improved style

**Comment by pixlwave** [comment]
Done
