### ISSUE TITLE
Not clear that you need to vote for your hated item?

### ISSUE THREAD

**Issue by benparsons** [emojirank/web#20]
Someone at work (@demoive) suggested it's not clear the need to click a second time.

**Comment by demoive** [comment]
Yea. I wasn't drawn to look at the changed title. Maybe some sort of animation could help with this.

**Comment by pixlwave** [comment]
Do the placeholder like/hate images help with this? I suspect they can be too far down the screen on mobile at times anyway but just wondering.

**Comment by benparsons** [comment]
I think it helps

**Comment by demoive** [comment]
It helps, but in a way that still makes *me* figure it out if it's not clear (which I don't think it is off the bat). Ideally we can get it to a place where there's no doubt about what the next action should be. But for the time being, maybe this isn't a priority.

**Comment by pixlwave** [comment]
I'd say this _is_ a priority Just tested this out on someone and got the following response!

> Lol not sure I understand what I'm doing

> Ah! Got it, the first tap is to select your like, the second tap is for hate

> I scrolled up and noticed the question changed

Will fix!

**Comment by pixlwave** [comment]
What do you think to something link this?
![mode](https://cloud.githubusercontent.com/assets/6060466/23078953/a412e6c4-f542-11e6-8b47-bc7bd475e2d1.gif)

**Comment by demoive** [comment]
These are really great improvements. Especially the quickly appearing modal for what the next action needs to be. The placeholder text+dotted line in the trays are a nice touch as well. Ship it! :-D

**Comment by pixlwave** [comment]
@benparsons So how do you make a div float on top and central on a page? That was just a quick mock-up in Motion 🤔

**Comment by benparsons** [comment]
@pixlwave we already have jQuery on the page. You could create an overlay which is normally hidden, then use show() (http://api.jquery.com/show/) to animate it in. There is a callback on complete, at which point we animate it out again.

**Comment by pixlwave** [comment]
Ok cool, but it was really the overlay bit that I was stuck with :man_shrugging:

**Comment by pixlwave** [comment]
Ok done, can't figure out why `fadeIn()` doesn't get called initially - maybe I've put the `.hide()` in the wrong lifecycle method?
But this works and looks better than it was without it.

**Comment by benparsons** [comment]
Love it. Yeah I'm not sure either would need to step through and see. Whatever, this works well
