### ISSUE TITLE
Idea: glyph score

### ISSUE THREAD

**Issue by benparsons** [emojirank/web#24]
glyph score is calculated as:

`(glyph_likes - glyph_hates) / (emoji_total_likes + emoji_total_hates) * 200`

This should give a score 0-100 (does this work?)

purpose of this score is to give a score for glyphs across emojis.

**Comment by pixlwave** [comment]
Better described as
`(glyph_likes - glyph_hates) / (emoji_total_likes + emoji_total_hates) * 200`

**Comment by benparsons** [comment]
This is implemented per-glyph. We're still short on a lot of votes though.
