### ISSUE TITLE
Variations

### ISSUE THREAD

**Issue by pixlwave** [emojirank/web#8]
Treat skin colour modifiers as variations of the same character. These are their codes:
U+1F3FB
U+1F3FC
U+1F3FD
U+1F3FE
U+1F3FF

**Comment by pixlwave** [comment]
Have a dropdown presented on any characters with variations so the user can switch and preview each colour, falling back to the default character if the vendor doesn't provide the variation.

**Comment by benparsons** [comment]
What do we still think about this idea? I'm happy with the current "flat" implementation, would rather not change to this.

**Comment by pixlwave** [comment]
I was thinking about this last night. All that we need to keep this working well would be a less random next-glyph algorithm. Say, we add the official emoji group to each glyph in the table ("Smileys & People", "Animals & Nature", "Food & Drink", etc, etc), first select a random group, and then select a random glyph from that group. Presumably that would help fix the fact that would result in more animals, food etc being shown over all.

There's an easier to view overview here for reference: http://unicode.org/emoji/charts/emoji-ordering.html

Edit: probably close this and open a separate issue if you agree, not like this is essential right now.

**Comment by benparsons** [comment]
ok let's do that. you know the / random selector chooses from the first 1024 emojis, so that's already an improvement. We can open a new task for /next improvements
